/* Automatically generated by './build/bin/build-entry.js' */

import Avatar from '../packages/avatar/index.js'
import Card from '../packages/card/index.js'
import Form from '../packages/form/index.js'
import LazySelect from '../packages/lazy-select/index.js'
import List from '../packages/list/index.js'
import Popconfirm from '../packages/popconfirm/index.js'
import Popover from '../packages/popover/index.js'
import Table from '../packages/table/index.js'
import TimelineItem from '../packages/timeline-item/index.js'
import Timeline from '../packages/timeline/index.js'
import Tooltip from '../packages/tooltip/index.js'
import TreeSelect from '../packages/tree-select/index.js'

const components = [
  Avatar,
  Card,
  Form,
  LazySelect,
  List,
  Popconfirm,
  Popover,
  Table,
  Timeline,
  TimelineItem,
  Tooltip,
  TreeSelect
]

const install = function(Vue) {
  components.forEach((component) => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  Avatar,
  Card,
  Form,
  install,
  LazySelect,
  List,
  Popconfirm,
  Popover,
  Table,
  Timeline,
  TimelineItem,
  Tooltip,
  TreeSelect
}
