/* Automatically generated by './build/bin/build-entry.js' */

import './styles/common.less'



const components = [
  
]
const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  install,

}
